#server:
 # port: 3355
spring:
  application:
    name: winery-config-client
#eureka:
 # client: #客户端注册进eureka服务列表内
  #  service-url:
   #   defaultZone: http://localhost:1111/eureka

       #defaultZone: http://localhost/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
